/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d0e1037f-a1e2-4e25-b47d-c9da91564bc7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_rGkieYXsd",
    "aws_user_pools_web_client_id": "3t0t0d4ik37fmcsc6mglo5q196",
    "oauth": {}
};


export default awsmobile;
